### ISSUE TITLE
Api migrations

### ISSUE THREAD

**Issue by uv0id** [md-y/mangadex-full-api#18]
Hey, it's not a big thing but, i'd like to let you know this: https://mangadex.org/thread/351011

**Comment by md-y** [comment]
I saw this a update and am working on migrating. A good majority of the web parsing can be removed so I need to change a lot and it may take a bit.

**Comment by emeraldraspberry** [comment]
What is the status of the migration work? I may help with transitioning current structures such as chapter.js to use the new API v2 if needed via pull request within a month.

**Comment by md-y** [comment]
There isn't much too migrate until Mangadex V5 is out, but there may be new endpoints/fields from the V2 API that are currently not being used by the program. I don't know if there are any of them missing other than the ones that are still using the old API or web parsing (which I am currently migrating from), so if you do see any missing feel free to make a pull request.
