### ISSUE TITLE
I just need a little help in understanding. (not a issue)

### ISSUE THREAD

**Issue by Kissu-coder** [md-y/mangadex-full-api#22]
https://github.com/md-y/mangadex-full-api#Chapter

How am i supposed to get the latest chapter id/link/volume.

can anyone please give me an example. thx

**Comment by ionutionoi** [comment]
You could try something like this
```
new api.Manga().fillByQuery('solo leveling')
	.then(manga => {
		console.log(manga.chapters[0]);
	});
```
`manga.chapters` returns an array which contains the chapter ID which you can use to get more info.
This is how the response looks like: 
```
Chapter {
  id: 1186824,
  type: undefined,
  url: 'https://mangadex.org/chapter/1186824',
  link: 'https://mangadex.org/chapter/1186824',
  timestamp: 1611798622,
  volume: 2,
  chapter: 137,
  title: '',
  language: undefined,
  parentMangaID: undefined,
  groups: [],
  commentCount: 3,
  pages: [],
  saverPages: [],
  views: undefined
} 
```
In my case, the first element seems to be the latest chapter, now if you want detailed info about it you can do something like 
`manga.chapters[0].id` and you get the chapter id which you can use as in the example below.
```
const chapter = await new Chapter(527948, true);
console.log(`This chapter is in ${language[chapter.language]}`);
```
I do not claim that this is a good, or even the right way of doing this, this is just something I put together quickly. I hope it is of some help to you.

**Comment by Kissu-coder** [comment]
Oh. Now I understood.
Tysm for the help.
