### ISSUE TITLE
manga.getFullURL("cover") returning an invalid url

### ISSUE THREAD

**Issue by s0hv** [md-y/mangadex-full-api#26]
Calling `manga.GetFullURL("cover")` incorrectly concatenates the cover to produce an url that looks like this `https://mangadex.orghttps://mangadex.org/images/manga/20882.jpg`. 
`manga.cover` however returns the correct url.

**Comment by md-y** [comment]
Fixed this by deprecating ```getFullURL``` all together. See [4.3.0](https://github.com/md-y/mangadex-full-api/releases/tag/4.3.0)
