### ISSUE TITLE
Breaking change in data returned by mangadex.org api

### ISSUE THREAD

**Issue by mftb0** [md-y/mangadex-full-api#3]
For some chapter requests mangadex.org has started returning a url fragment in the Chapter.server property (just the beginning of the url path).  This breaks some of mangadex-full-api's calls like Chapter.fill().  Example - https://mangadex.org/api/chapter/591097.

Specifically when the Chapter.pages array is populated in Chapter.parse() you end up with relative urls.  Not sure what the best fix for mangadex-full-api would be.  I was able to work around it by just iterating over Chapter.pages and if the value started with "/", prepending the value returned by Chapter.getFullURL("foo").

Thanks again, mangadex-full-api, continues to be very useful, and easy to work with.

**Comment by md-y** [comment]
Thanks for the feedback! 
Looks like they are using a new image server from the home domain. I don't know if its a backup or a new server like the one Holo mentioned [here ](https://mangadex.org/thread/73148)though. Anyways, I also prepended the fragment with Mangadex's homepage.
