### ISSUE TITLE
Failed to retrieve session id.

### ISSUE THREAD

**Issue by cCurmudgeon** [md-y/mangadex-full-api#31]
I used dotenv to store email and password but I tried just providing the email and password no luck.

```javascript
api.agent.login(process.env.MDUSER, process.env.MDPASS, false).then(async () => {
})
```

But when I do execute console returns me this
```$HOME/tofolder/node_modules/mangadex-full-api/src/structure/agent.js:99
                else reject(new Error("Failed to retrieve session id."));
                            ^

Error: Failed to retrieve session id.
```
So I was guessing this problem was related to the email and password used.
Please help me out!

**Comment by md-y** [comment]
Check if the username and password are correct. I can't replicate your issue, so either that's the problem or the login for Mangadex was fixed in the last six hours.

**Comment by EJBEAN2op** [comment]
been happening that for me , apparently api died after the prolonged attack that happened a few days ago

**Comment by EJBEAN2op** [comment]
ye figured it out , you need a account which doesnt use fake / temporary emails (since mangadex auto bans fake / bot accounts after the update)
