### ISSUE TITLE
List.get('id') required user login to get the list

### ISSUE THREAD

**Issue by johnlim5847** [md-y/mangadex-full-api#42]
Hi, when I tried to execute the code below. 

```js
// Get custom list
   const customList = await MFA.List.get(
     "8018a70b-1492-4f91-a584-7451d7787f7a"
   );
```
I get the `APIRequestError: Not logged in.` error. 

But calling the Mangadex API directly `https://api.mangadex.org/list/8018a70b-1492-4f91-a584-7451d7787f7a` didn't throw any error.

**Comment by Curstantine** [comment]
Hmm it runs through util.auth.validateTokens()

**Comment by md-y** [comment]
Fixed in latest commit

(Forgot an if statement)
