### ISSUE TITLE
Mangadex has refactored the search API response

### ISSUE THREAD

**Issue by MxBlu** [md-y/mangadex-full-api#44]
Looks like Mangadex has changed fields in the response object from an API search (namely, Chapter.search(), though looks like its a more general issue).

src/util.js:178 throws an error since initialResponse doesn't have the field "result", which is now "data". 
```
 APIRequestError: The API did not respond the correct structure for a search request:
[object Object]
```
(BTW maybe JSON.stringify the response for printing)

Tried patching it but no dice, it generated empty Chapter objects as results. Looks like there's further patching to do.

**Comment by md-y** [comment]
Fixed in new release, 5.5.1
