### ISSUE TITLE
TypeScript error on UploadSession.commit()

### ISSUE THREAD

**Issue by MxBlu** [md-y/mangadex-full-api#46]
Can't wrap my head around this one, for some reason, TS can't see the def of `Chapter` in the return type of `commit()`.
I'm on TS 4.4.2, but I also note the error when using the version in package.json (4.1.3).

![image](https://user-images.githubusercontent.com/9107817/133428845-72664142-9e6e-4ad1-9c85-aa2dbb2a13fd.png)

Also FYI there's also some rest parameters that are marked as optional, which the compiler doesn't like. No need for them to be, so can get rid of them:
![image](https://user-images.githubusercontent.com/9107817/133429664-780cbadc-f63f-4c5b-970d-e33ede720224.png)

I'd PR it but no point of only fixing most of the TS errors and not all of them.

**Comment by md-y** [comment]
The chapter issue is due to the poor script that was compiling ```index.d.ts```. It's now handled by another module.

Both issues are fixed for 5.6.0
