### ISSUE TITLE
GetReadablePages: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by Node231** [md-y/mangadex-full-api#52]
Hello, thanks for the great library. Ran into this issue today (on latest version):

![image](https://user-images.githubusercontent.com/10150101/148667202-60d47bee-ead5-4e60-8a32-800d2031637d.png)

from this Chapter object:
![image](https://user-images.githubusercontent.com/10150101/148667224-11e4fe66-c778-4c78-b156-c520c52d3611.png)
(these pages previously existed)

Not sure if this an issue with the library, or if something is up with Mangadex

**Comment by ShambaC** [comment]
Its probably because of the update MD made to their API yesterday.
![image](https://user-images.githubusercontent.com/38806897/148669356-82167e36-f076-42d5-a87e-a190fdd044fb.png)

**Comment by Node231** [comment]
> Its probably because of the update MD made to their API yesterday. ![image](https://user-images.githubusercontent.com/38806897/148669356-82167e36-f076-42d5-a87e-a190fdd044fb.png)

Good find, looking into a little more it looks like the update makes you use the `at-home` endpoint
![image](https://user-images.githubusercontent.com/10150101/148670096-cf2292ce-145c-4813-a4d0-2bcbbb70486f.png)

**Comment by md-y** [comment]
Just pushed a commit to fix this 7f672d6f9c16794071f99fd5647aada2e7a1afeb.

Will make a new release with this change plus some other changes as soon as I can.
