### ISSUE TITLE
way to get total results

### ISSUE THREAD

**Issue by Nowaaru** [md-y/mangadex-full-api#57]
###### (i'd first like to start off with a massive thank-you. this api is very useful for anything md related)

as far as i can tell, this api does not give the user the `total` field when calling `.search(...)`. 
this is detrimental to those who wish to make any method to navigating
manga since there is no indicator that shows when there are no more results outside of
making an extra request to check; but this applies especially to methods - specifically pagination -
where the end (and some in-between) is exposed.

the fundamental issue with this implementation unfortunately is that this would be a very breaking
change since the return data would not be an array but instead an object with a limit (and etc..) field 
and then the data field.

so instead of jumping through those eight-thousand hurdles, i think a method that gets the total amount of items in a class would be better.. at the expense of making a request to get the total amount of items.

thank you

**Comment by md-y** [comment]
Added in 5.9.0
