### ISSUE TITLE
Can't resolve 'fs' in node_modules\mangadex-full-api\src

### ISSUE THREAD

**Issue by Definkle** [md-y/mangadex-full-api#66]
I'm trying to work with the api but I have this error and I can't continue.
`./node_modules/mangadex-full-api/src/auth.js:12:7-20 - Error: Module not found: Error: Can't resolve 'fs' in 'C:\Work\projects\say-manga-reader\node_modules\mangadex-full-api\src'
`

**Comment by md-y** [comment]
What version of node are you using, and are you using Typescript or some other framework?

```fs``` is a built-in module so it's very surprising it cant be resolved.

**Comment by Definkle** [comment]
My node is v16.15.1 and I'm using Angular v14 so typescript.

**Comment by md-y** [comment]
It's probably an issue with angular/webpack like the one discussed [here](https://stackoverflow.com/questions/57161839/module-not-found-error-cant-resolve-fs-in)
